### PR TITLE
update package.json with newer graceful-fs version

### PR DESCRIPTION
**Pull request by ismail-codinglab**
update package.json with newer graceful-fs version this fixes memory leak in older graceful versions

### CODE REVIEW

**Comment by RyanZim** [comment]
The `^` in the version number should install the latest version of graceful-fs v4 line (i.e. anything less than v5.0.0), which is currently the latest version of graceful-fs.

Is there any specific reason this needs to be changed?

**Comment by issy123** [comment]
Older versions contain a memory leak which is fixed by this version.

There were a list of npm packages using this, one of which is this package.

**Comment by RyanZim** [comment]
Unless your lockfile is pinning to an old version, klaw should be using the latest version of graceful-fs as-is. I'm not understanding why the change is needed,

**Comment by RyanZim** [comment]
Graceful-fs removed in https://github.com/jprichardson/node-klaw/pull/43.

**Pull request closed without merging**
