### PR TITLE
Use faster self.paths.push strategy

### PR DESCRIPTION
**Pull request by hulkish**

### CODE REVIEW

**Comment by jprichardson** [comment]
@hulkish thank you. Please add a comment above the line as to why this is done - I don't think it'll be obvious to future devs. Then squash commits. Thanks again.

**Comment by hulkish** [comment]
@jprichardson ok cool, how's that?

**Comment by jprichardson** [comment]
Great, thanks! @RyanZim please publish patch when you can.

**Comment by RyanZim** [comment]
Published as 2.1.1 :tada:

**Pull request merged**
