### PR TITLE
Fix walk so that it continues to walk even after errors

### PR DESCRIPTION
**Pull request by hydrabolt**
But still emits errors

### CODE REVIEW

**Comment by jprichardson** [comment]
Awesome, thanks for the PR! Will you run `npm test` and clean up the errors on your end and then push?

**Comment by hydrabolt** [comment]
Done! :)

**Comment by jprichardson** [comment]
Ok, I see what's going on... I'm gonna add a test.

**Comment by jprichardson** [comment]
Ok, I'm actually gonna close this, but I've pushed a fix and will publish shortly. If it wasn't for your PR though, I wouldn't have seen the issue so clearly :p So thank you!

**Pull request closed without merging**
