### PR TITLE
add broken symlink test

### PR DESCRIPTION
**Pull request by kellyselden**
I'm trying to diagnose a broken symlinks issue. I thought the issue was here so I started with a failing test. Looks like everything works here, but it probably wouldn't hurt to include this test for the future.

### CODE REVIEW

**Comment by kellyselden** [comment]
Not sure what's up with the linter.

**Comment by RyanZim** [comment]
It's that stupid standard-markdown. More hassle than it's worth. PR welcome to remove it.

**Comment by RyanZim** [comment]
Finally got a PR in for it myself: https://github.com/jprichardson/node-klaw/pull/35. Can rebase and merge this after that one is merged.

**Comment by RyanZim** [comment]
Landed in a3c7780507d46cb4d45db67393369ce6cae45315.

**Comment by kellyselden** [comment]
Thanks.

**Pull request closed without merging**
